FROM node:23.5.0

# Update apt and install git
RUN echo "Updating apt and installing git..." 
RUN apt install -y git

# Check if /app exists, and remove it if so
RUN echo "Checking if /app directory exists..." && if [ -d "/app" ]; then echo "/app exists, removing it..."; rm -rf /app; else echo "/app does not exist."; fi

# Set environment variables
ENV GIT_URL=https://github.com/Baymax1211/portfolio.git

# Log the repository URL being used
RUN echo "Cloning repository from Github..."

# Clone the repository
RUN git clone --depth=1 --branch=master ${GIT_URL} /app

COPY .env /app/

# Set the working directory to /app
WORKDIR /app

# Install dependencies with npm
RUN echo "Installing dependencies with npm..." 
RUN npm install --force

# Build the application
RUN echo "Building the application..." 
RUN npm run build

# Start the application
RUN echo "Starting the application..." 
EXPOSE 3000
CMD [ "env", "npm", "run", "start" ]